name: CI

on: [push]

jobs:
  test-v1:
    name: Test v1
    runs-on: ubuntu-20.04
    services:
      clickhouse:
        image: yandex/clickhouse-server:21.11
        env:
          CLICKHOUSE_USER: test
          CLICKHOUSE_PASSWORD: test
          CLICKHOUSE_DB: test
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        working-directory: v1
        run: go test -v ./...
        env:
          DB_HOST: 127.0.0.1:9000
          DB_USER: test
          DB_PASSWORD: test
          DB_NAME: test
  test-v2:
    name: Test v2
    runs-on: ubuntu-20.04
    services:
      clickhouse:
        image: yandex/clickhouse-server:21.11
        env:
          CLICKHOUSE_USER: test
          CLICKHOUSE_PASSWORD: test
          CLICKHOUSE_DB: test
        ports:
          - 9000:9000
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        working-directory: v2
        run: go test -v ./...
        env:
          DB_HOST: 127.0.0.1:9000
          DB_USER: test
          DB_PASSWORD: test
          DB_NAME: test